---
title: "Berkeley Rental Rates"
format: gfm
---

## Data viz topics

1. Confusing comparison of two rates, each with a different denominator in an original analysis.
2. Secondary reporting that conflates the two denominators.

The Anti-Eviction Mapping Project produced an in-depth report, "Densifying Berkeley: Potential Impacts on Displacement and Equity". On p. 25, they feature a bar chart (berkeley-rental-rates.png) puts ethnicity of repondents along the x-axis, and for each ethnicity, provides the proportion of that ethnicity who rent right next to the proportion of total residents that are of that ethnicity. Pairing rates with different denominators can lead to conflation and misinterpretation. The description of these rates in the accompanying text draws attention to the comparison between these rates.

> There are distinct differences in percent of renters across racial and ethnic lines; groups whose populations are overall minorities in the City of Berkeley have higher proportions of renters (as opposed to homeowners). For instance, 74% Black residents are renter households, but Black residents make up only about 8% of Berkeley’s total population. 69% of Latinx households are renters, but they make up 12.3% of the total population. Non-Latinx White populations had the lowest proportion of renters, at 50.1%, yet make up the majority of the city’s population at 53%.

It's unclear that this is a meaningful or important comparison.

This report was covered in Berkeleyside, the local newspaper, misinterpret these rates.

> A chart from the report shows that while Black people make up only 8% of the cityʼs population, they make up 74% of renter households. Credit: Anti-Eviction Mapping Project

## Improvements

Remove the 

